import ToastProvider from "@/components/ToastProvider";
import Header from "@/components/admin/Header";
import Sidebar from "@/components/admin/Sidebar";
import "../globals.css";
import { getServerSession } from 'next-auth/next';
import { authOptions } from "../api/auth/[...nextauth]/route";
export const metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};


export default async function DashboardLayout({ children }) {
const session = await getServerSession(authOptions);
    if (!session || !session.user?.email) {
        return (
            <div>
                This is protected and you do not have access to it.
            </div>
        )
    }
    return (
        <html lang="en" suppressHydrationWarning>
            <body className="">
                <div className="min-h-screen max-h-screen">
                    <Sidebar>
                        <Header title={metadata.title} />
                        <ToastProvider />
                        {children}
                    </Sidebar>
                </div>
            </body>
        </html>
    );
}