import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./Provider";
import Link from "next/link";
import { Button } from '@nextui-org/button';
import ThemeSwitcher from "@/components/ThemeSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <header className="py-6">
                        <nav className="container flex items-center justify-between">
                            <ul>
                                <li>
                                    <Link href="/">Home</Link>
                                </li>
                            </ul>
                            <ThemeSwitcher />
                        </nav>
                    </header>
                    <main>{children}</main>
                </Providers>
            </body>
        </html>
    );
}
