import ToastProvider from "@/components/ToastProvider";
import Header from "@/components/admin/Header";
import Sidebar from "@/components/admin/Sidebar";
import "../globals.css";

export const metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};


export default function DashboardLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <div className="bg-gray-200 min-h-screen max-h-screen">
                    <Sidebar>
                        <Header title={metadata.title} />
                        <ToastProvider />
                        {children}
                    </Sidebar>
                </div>
            </body>
        </html>
    );
}