import ToastProvider from "@/components/ToastProvider";
import Header from "@/components/admin/Header";
import Sidebar from "@/components/admin/Sidebar";
import "../globals.css";
import { Providers } from "../Provider";

export const metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};


export default function DashboardLayout({ children }) {
    return (
        <html lang="en" >
            <body className="dark:bg-black dark:text-white text-black bg-blue-100">
                <Providers>
                    <div className="min-h-screen max-h-screen">
                        <Sidebar>
                            <Header title={metadata.title} />
                            <ToastProvider />
                            {children}
                        </Sidebar>
                    </div>
                </Providers>
            </body>
        </html>
    );
}